# Generated by Django 5.0 on 2024-11-27 13:54

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('short_bio', models.CharField(blank=True, max_length=160, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar', models.CharField(blank=True, max_length=200, null=True)),
                ('banner', models.CharField(blank=True, default='https://fastly.picsum.photos/id/91/800/500.jpg?hmac=J_kCOn2MZlDuJIb_rU14DYnb6HMv55ynWirbSF9l8f0', max_length=200, null=True)),
                ('registration_finish', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(related_name='following', to='app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.TextField(max_length=500)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('likes', models.ManyToManyField(related_name='comment_likes', to='app.profile')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.profile')),
                ('unlikes', models.ManyToManyField(related_name='comment_unlikes', to='app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=5000)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('contributors', models.ManyToManyField(related_name='stories_contributed_to', to='app.profile')),
                ('likes', models.ManyToManyField(related_name='likers', to='app.profile')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarkers', to='app.story'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200, null=True)),
                ('banner', models.CharField(max_length=200, null=True)),
                ('contributors', models.ManyToManyField(related_name='topics_contributed_to', to='app.profile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('followers', models.ManyToManyField(related_name='topics_following', to='app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='story',
            name='topics',
            field=models.ManyToManyField(related_name='stories', to='app.topic'),
        ),
    ]
