# Generated by Django 5.0 on 2024-11-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_likes_alter_comment_unlikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_created', to='app.profile'),
        ),
    ]
