# Generated by Django 5.1.3 on 2024-12-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_storyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
