# Generated by Django 5.1.3 on 2024-12-04 16:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
