# Generated by Django 5.1.3 on 2024-12-04 16:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_story_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
