# Generated by Django 5.1.3 on 2024-12-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='unique_views',
            field=models.ManyToManyField(blank=True, related_name='viewers', to='app.profile'),
        ),
    ]
