# Generated by Django 5.1.3 on 2024-12-09 20:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_featuringstory_image_featuringstory_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuringstory',
            name='intro_to_story',
            field=tinymce.models.HTMLField(default='Zola Robinson had also belive that art was more than a medium of expression it a tool for Libration'),
            preserve_default=False,
        ),
    ]
