# Generated by Django 5.1.3 on 2024-12-13 18:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_profile_newsletter_opt_in_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
