# Generated by Django 5.1.3 on 2025-03-30 00:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_storyimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillist',
            options={'verbose_name_plural': 'Email Lists'},
        ),
        migrations.AlterModelOptions(
            name='featuringstory',
            options={'verbose_name': 'Featuring Story', 'verbose_name_plural': 'Featuring Stories'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'NewsLetters'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storyimage',
            name='alt',
            field=models.CharField(default='there is not description for this image', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featuringstory',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='stories_liked', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn'), ('r', 'Review')], default='d', max_length=1),
        ),
    ]
