#!/usr/bin/env bash
#  a Bash script that generates a MySQL dump and creates a compressed archive out of it.


pwd="$1"
# create the dump
sudo sh -c "mysqldump -u root -p'$pwd' --all-databases > backup.sql"

# create a archive from it
tar -zcv -f "$(date +"%d-%m-%y").tar.gz" backup.sql